"""Render :class:`TasteRule` lists as editor-friendly rule files.

These exporters let users drop their evolved taste straight into the
configuration files consumed by modern AI coding agents:

* ``cursor``   - ``.cursorrules`` (Cursor IDE)
* ``windsurf`` - ``.windsurfrules`` (Windsurf / Codeium)
* ``claude``   - ``CLAUDE.md`` (Claude Code, Anthropic)
* ``copilot``  - ``.github/copilot-instructions.md`` (GitHub Copilot)
* ``markdown`` - generic Markdown bullet list
* ``text``     - plain text bullet list (no Markdown)

The output is fully deterministic so it can be safely committed to git.
"""
from __future__ import annotations

from typing import Callable, Dict, Iterable, List

from .exceptions import ConfigurationError
from .models import TasteRule

_DEFAULT_HEADER = (
    "# Personal coding preferences\n\n"
    "These rules were learned from the developer's review feedback by\n"
    "[PersonalEvoTaste](https://github.com/xzfnn/PersonalEvoTaste).\n"
    "Follow them whenever you generate or modify code in this repository.\n"
)

_TOOL_HEADERS: Dict[str, str] = {
    "cursor": (
        "# Cursor rules - generated by PersonalEvoTaste\n\n"
        "When generating code, strictly follow the personal preferences below.\n"
        "Rules are sorted by importance (highest first).\n"
    ),
    "windsurf": (
        "# Windsurf rules - generated by PersonalEvoTaste\n\n"
        "When generating code, strictly follow the personal preferences below.\n"
        "Rules are sorted by importance (highest first).\n"
    ),
    "claude": (
        "# Project preferences for Claude\n\n"
        "These instructions were generated by PersonalEvoTaste from review\n"
        "feedback the developer has given over time. Treat them as project-\n"
        "specific style guidance and follow them in every response.\n"
    ),
    "copilot": (
        "# Copilot custom instructions\n\n"
        "These instructions were generated by PersonalEvoTaste. Apply them to\n"
        "every code suggestion produced for this repository.\n"
    ),
    "markdown": _DEFAULT_HEADER,
}


def _format_markdown(rules: List[TasteRule], header: str) -> str:
    if not rules:
        return header + "\n_(No taste rules learned yet.)_\n"
    lines = [header, "## Rules\n"]
    for i, r in enumerate(rules, 1):
        meta_bits = [f"weight={r.weight:.2f}", f"hits={r.hits}"]
        if r.project:
            meta_bits.append(f"project=`{r.project}`")
        meta = ", ".join(meta_bits)
        lines.append(f"{i}. **{r.rule}**  ")
        if r.reason:
            lines.append(f"   - _why:_ {r.reason}")
        lines.append(f"   - _meta:_ {meta}")
    return "\n".join(lines) + "\n"


def _format_text(rules: List[TasteRule], header: str) -> str:
    plain_header = header.replace("# ", "").replace("**", "")
    if not rules:
        return plain_header + "\n(No taste rules learned yet.)\n"
    lines = [plain_header, "Rules (most important first):", ""]
    for i, r in enumerate(rules, 1):
        lines.append(f"{i}. {r.rule}")
        if r.reason:
            lines.append(f"   why: {r.reason}")
        suffix = f"weight={r.weight:.2f} hits={r.hits}"
        if r.project:
            suffix += f" project={r.project}"
        lines.append(f"   {suffix}")
    return "\n".join(lines) + "\n"


_FORMATTERS: Dict[str, Callable[[List[TasteRule], str], str]] = {
    "cursor": lambda rules, h: _format_markdown(rules, h),
    "windsurf": lambda rules, h: _format_markdown(rules, h),
    "claude": lambda rules, h: _format_markdown(rules, h),
    "copilot": lambda rules, h: _format_markdown(rules, h),
    "markdown": lambda rules, h: _format_markdown(rules, h),
    "text": lambda rules, h: _format_text(rules, h),
}

SUPPORTED_FORMATS: List[str] = sorted(_FORMATTERS.keys())


def render_rules(
    rules: Iterable[TasteRule],
    fmt: str = "markdown",
    *,
    header: str = "",
) -> str:
    """Render the given rules using the named template.

    Parameters
    ----------
    rules:
        Iterable of :class:`TasteRule` objects, already filtered/sorted
        the way you want them to appear in the output.
    fmt:
        One of :data:`SUPPORTED_FORMATS`.
    header:
        Optional override for the introductory text.  When empty, a
        sensible default for the chosen format is used.
    """
    fmt = fmt.lower()
    formatter = _FORMATTERS.get(fmt)
    if formatter is None:
        raise ConfigurationError(
            f"Unknown format {fmt!r}; expected one of {SUPPORTED_FORMATS}"
        )
    rules_list = list(rules)
    chosen_header = header or _TOOL_HEADERS.get(fmt, _DEFAULT_HEADER)
    return formatter(rules_list, chosen_header)
